INSERT INTO questions(question, facteur) VALUES("Vous êtes prêt ?",	0);
INSERT INTO questions(question, facteur) VALUES("Avez-vous de la fièvre ces derniers  jours ?",	1.2);
INSERT INTO questions(question, facteur) VALUES("Avez-vous des difficultés respiratoires ?",1.1);
INSERT INTO questions(question, facteur) VALUES("Toussez-vous ces derniers jours ?",2);
INSERT INTO questions(question, facteur) VALUES("Présentez-vous de la grippe  ?",2.5);
INSERT INTO questions(question, facteur) VALUES("Avez-vous des courbatures ?",2);
INSERT INTO questions(question, facteur) VALUES("Avez-vous des maux de tête ?",1.2);
INSERT INTO questions(question, facteur) VALUES("Avez-vous récement eu des frissons ?",1);
INSERT INTO questions(question, facteur) VALUES("Avez-vous des troubles digestif ?",1);
INSERT INTO questions(question, facteur) VALUES("Avez-vous été en contact avec une personne qui a le COVID-19 ?",8.8);
INSERT INTO questions(question, facteur) VALUES("Avez-vous récement voyagé dans un pays contaminé par le COVID-19 ?",4.2);
